# Install and configure GNU/Linux Kernel
---

- block:
    - dynamic_defaults:
        hostvars: '{{ hostvars[inventory_hostname] }}'
        defaults: '{{ kernel_dynamic_defaults }}'
        must_match: true

    - name: Get current GNU/Linux Kernel configuration
      kernel_facts:
      when: kernel_get_config|bool
  tags: [kernel, always]

- name: Install GNU/Linux kernel packages
  ansible.builtin.package:
    name: '{{ kernel_packages }}'
    state: present
  become: true
  tags: [kernel, packages]
